type Coordinates {
    lat: String!
    lng: String!
}

type Address {
    street: String!
    suite: String!
    city: String!
    zipcode: String!
    geo: Coordinates!
}

type Company {
    name: String!
    catchPhrase: String!
    bs: String!
}

type User {
    id: Int!
    name: String!
    username: String!
    email: String!
    address: Address!
    phone: String!
    website: String!
    company: Company!
    posts: [Post]
    albums: [Album]
}

type Post {
    userId: Int!
    id: Int!
    title: String!
    body: String!
    user: User
}

type Comment {
    postId: Int!
    id: Int!
    name: String!
    email: String!
    body: String!
    post: Post
}

type Album {
    userId: Int!
    id: Int!
    title: String!
    user: User
}

# Input types for mutations
input CoordinatesInput {
    lat: String!
    lng: String!
}

input AddressInput {
    street: String!
    suite: String!
    city: String!
    zipcode: String!
    geo: CoordinatesInput!
}

input CompanyInput {
    name: String!
    catchPhrase: String!
    bs: String!
}

input UserInput {
    name: String!
    username: String!
    email: String!
    address: AddressInput!
    phone: String!
    website: String!
    company: CompanyInput!
}

input PostInput {
    userId: Int!
    title: String!
    body: String!
}

input CommentInput {
    postId: Int!
    name: String!
    email: String!
    body: String!
}

input AlbumInput {
    userId: Int!
    title: String!
}

# Queries and mutations

type Query {
    users: [User!]!
    user(id: Int!): User
    posts: [Post!]!
    post(id: Int!): Post
    comments: [Comment!]!
    comment(id: Int!): Comment
    albums: [Album!]!
    album(id: Int!): Album
}

type Mutation {
    addUser(user: UserInput!): User
    editUser(id: Int!, user: UserInput!): User
    removeUser(id: Int!): User
    addPost(post: PostInput!): Post
    editPost(id: Int!, post: PostInput!): Post
    removePost(id: Int!): Post
    addComment(comment: CommentInput!): Comment
    editComment(id: Int!, comment: CommentInput!): Comment
    removeComment(id: Int!): Comment
    addAlbum(album: AlbumInput!): Album
    editAlbum(id: Int!, album: AlbumInput!): Album
    removeAlbum(id: Int!): Album
}
